server:
  port: 8079
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 20
      minimum-idle: 20
    name: mall_datasource
    url: xxx
    username: xxx
    password: xxx
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  mail:
    default-encoding: utf-8
    host: xxx
    password: xxx
    port: 587
    properties:
      mail:
        smtp:
          auth: true
    username: xxx@xxx.com
  redis:
    host: 127.0.0.1
    port: 6379

file:
  upload:
    dir: /xxx/xxx/xxx/
    ip: xxx
    uri: xxx:8079
mybatis:
  mapper-locations: classpath:mappers/*.xml
icode: ABCDE
