server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 10
      minimum-idle: 5
    name: mall_datasource
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1634585729
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    password: 123123
    port: 587
    properties:
      mail:
        smtp:
          auth: true
    username: xxxx@xxxx.com
  redis:
    host: 127.0.0.1
    port: 6379

file:
  upload:
    dir: /Users/xxxx/myselfwork/mall-file/
    ip: 127.0.0.1
    uri: 127.0.0.1:8081
icode: ABCDE
mybatis:
  mapper-locations: classpath:mappers/*.xml
